spring:
  application:
    name: weather-checker

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

weather:
  api:
    url: https://api.open-meteo.com
    geocoding-url: https://geocoding-api.open-meteo.com